version: '3.7'
services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
  
  api:
    image: 949191617935.dkr.ecr.cn-north-1.amazonaws.com.cn/jm-app/jm-micro:latest
    command:
      - "--registry=etcd"
      - "--registry_address=etcd:2379"
      - "--log_level=DEBUG"
      # 如果使用 Logstash 格式日志，取消下一行注释
      # - "--log_format=LOGSTASH"
      - "--register_interval=5"
      - "--register_ttl=10"
      - "--client_pool_size=10"
      - "--server_name=com.jinmuhealth.platform.api"
      # 生产环境对外部署时使用 MicroSimple
      - "--metadata=X-Err-Style=MicroDetailed"
      - "--enable_tls"
      - "--tls_cert_file=/cert/localhost.crt"
      - "--tls_key_file=/cert/localhost.key"
      - "--tls_client_ca_file=/cert/root_ca.crt"
      - "--config_etcd_address=etcd:2379"
      - "api"
      - "--address=0.0.0.0:8080"
      - "--handler=rpc"
      - "--enable_rpc"
      - "--namespace=com.jinmuhealth.platform.srv"
      - "--enable_jwt"
      - "--jwt_max_exp_interval=600s"
    volumes: 
      - "./cert:/cert"
    depends_on:
      - etcd
    ports:
      - "8080:8080"

  web:
    image: 949191617935.dkr.ecr.cn-north-1.amazonaws.com.cn/jm-app/jm-micro:latest
    command:
      - "--registry=etcd"
      - "--registry_address=etcd:2379"
      - "--log_level=DEBUG"
      # 如果使用 Logstash 格式日志，取消下一行注释
      # - "--log_format=LOGSTASH"
      - "--register_interval=5"
      - "--register_ttl=10"
      - "--enable_tls"
      - "--tls_cert_file=/cert/localhost.crt"
      - "--tls_key_file=/cert/localhost.key"
      - "--server_name=com.jinmuhealth.platform.web"
      - "web"
      - "--namespace=com.jinmuhealth.platform.srv"
    volumes: 
      - "./cert:/cert"
    depends_on:
      - etcd
    ports:
      - "8082:8082" 
